"""crea festividades y afluencia historica

Revision ID: ddb2372e02a8
Revises: 7108081d207c
Create Date: 2026-08-29 07:39:00.288521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ddb2372e02a8'
down_revision: Union[str, Sequence[str], None] = '7108081d207c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('provincia', sa.String(length=80), nullable=True),
    sa.Column('distrito', sa.String(length=80), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('es_movil', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fuente', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('religiosa', 'costumbrista', 'civica', 'feria', 'nacional')", name='ck_festividad_tipo'),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='ck_festividad_fechas'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'fecha_inicio', 'distrito', name='uq_festividad_nombre_fecha_distrito')
    )
    op.create_index(op.f('ix_festividad_distrito'), 'festividad', ['distrito'], unique=False)
    op.create_index(op.f('ix_festividad_fecha_inicio'), 'festividad', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_festividad_provincia'), 'festividad', ['provincia'], unique=False)
    op.create_index('ix_festividad_rango', 'festividad', ['fecha_inicio', 'fecha_fin'], unique=False)
    op.create_table('afluencia_historica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('mes', sa.SmallInteger(), nullable=False),
    sa.Column('visitantes', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('anio BETWEEN 2000 AND 2100', name='ck_afluencia_anio'),
    sa.CheckConstraint('mes BETWEEN 1 AND 12', name='ck_afluencia_mes'),
    sa.CheckConstraint('visitantes >= 0', name='ck_afluencia_visitantes'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso_turistico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurso_id', 'anio', 'mes', name='uq_afluencia_recurso_periodo')
    )
    op.create_index(op.f('ix_afluencia_historica_recurso_id'), 'afluencia_historica', ['recurso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_afluencia_historica_recurso_id'), table_name='afluencia_historica')
    op.drop_table('afluencia_historica')
    op.drop_index('ix_festividad_rango', table_name='festividad')
    op.drop_index(op.f('ix_festividad_provincia'), table_name='festividad')
    op.drop_index(op.f('ix_festividad_fecha_inicio'), table_name='festividad')
    op.drop_index(op.f('ix_festividad_distrito'), table_name='festividad')
    op.drop_table('festividad')
    # ### end Alembic commands ###
