"""anade los meses de celebracion de las fiestas

Revision ID: 202548ca2ef5
Revises: 0e08657630e7
Create Date: 2026-08-30 14:52:38.051979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '202548ca2ef5'
down_revision: Union[str, Sequence[str], None] = '0e08657630e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurso_turistico', sa.Column('meses_de_celebracion', sa.ARRAY(sa.SmallInteger()), server_default='{}', nullable=False))
    op.alter_column('recurso_turistico', 'dias_de_celebracion',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recurso_turistico', 'dias_de_celebracion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('recurso_turistico', 'meses_de_celebracion')
    # ### end Alembic commands ###
