"""Añade a recurso_turistico lo que trae la ficha web del MINCETUR.

El CSV del inventario no publica descripción, horario ni precio, y durante
seis fases eso se declaró como una limitación de la fuente. Lo era del CSV: la
ficha web de cada recurso —cuya dirección ya estaba en `url_ficha`— sí los
trae.

Estas cuatro columnas guardan lo que la ficha añade y el CSV no tiene. Las
descripciones van a `descripcion_es`, los horarios a `horario_atencion` y los
conteos de visitantes a `afluencia_historica`, que ya existían vacías.

`ficha_leida_en` va junto al dato y no en una tabla aparte: la honestidad con
los datos exige poder decir «esto es de tal fecha» sin ir a buscarlo.


Revision ID: 0010c8bc61ba
Revises: 4b1c9d2ea375
Create Date: 2026-08-30 14:43:43.056436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0010c8bc61ba'
down_revision: Union[str, Sequence[str], None] = '4b1c9d2ea375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurso_turistico', sa.Column('tipo_de_ingreso', sa.String(length=120), nullable=True))
    op.add_column('recurso_turistico', sa.Column('epoca_propicia', sa.String(length=200), nullable=True))
    op.add_column('recurso_turistico', sa.Column('dias_de_celebracion', sa.String(length=200), nullable=True))
    op.add_column('recurso_turistico', sa.Column('ficha_leida_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurso_turistico', 'ficha_leida_en')
    op.drop_column('recurso_turistico', 'dias_de_celebracion')
    op.drop_column('recurso_turistico', 'epoca_propicia')
    op.drop_column('recurso_turistico', 'tipo_de_ingreso')
    # ### end Alembic commands ###
