"""crea usuarios y preferencias de viaje

Revision ID: 7108081d207c
Revises: 3f1515a2371d
Create Date: 2026-08-29 03:40:49.680003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7108081d207c'
down_revision: Union[str, Sequence[str], None] = '3f1515a2371d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('idioma_preferido', sa.String(length=5), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("idioma_preferido IN ('es', 'en')", name='ck_usuario_idioma'),
    sa.CheckConstraint("rol IN ('visitante', 'operador', 'proveedor', 'gestor', 'administrador')", name='ck_usuario_rol'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_rol'), 'usuario', ['rol'], unique=False)
    op.create_table('preferencia_viaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('presupuesto_soles', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('intereses', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('movilidad', sa.String(length=24), nullable=False),
    sa.Column('requiere_accesibilidad', sa.Boolean(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('ritmo', sa.String(length=16), nullable=False),
    sa.Column('distrito_origen', sa.String(length=80), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("idioma IN ('es', 'en')", name='ck_preferencia_idioma'),
    sa.CheckConstraint("movilidad IN ('caminando', 'transporte_publico', 'taxi', 'combinado')", name='ck_preferencia_movilidad'),
    sa.CheckConstraint("ritmo IN ('relajado', 'moderado', 'intenso')", name='ck_preferencia_ritmo'),
    sa.CheckConstraint('cardinality(intereses) > 0', name='ck_preferencia_intereses_no_vacios'),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='ck_preferencia_fechas'),
    sa.CheckConstraint('presupuesto_soles >= 0', name='ck_preferencia_presupuesto'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferencia_viaje_creado_en'), 'preferencia_viaje', ['creado_en'], unique=False)
    op.create_index(op.f('ix_preferencia_viaje_usuario_id'), 'preferencia_viaje', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preferencia_viaje_usuario_id'), table_name='preferencia_viaje')
    op.drop_index(op.f('ix_preferencia_viaje_creado_en'), table_name='preferencia_viaje')
    op.drop_table('preferencia_viaje')
    op.drop_index(op.f('ix_usuario_rol'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
