"""crea valoraciones y registro de evidencia

Revision ID: 9e5f48ead726
Revises: 1f3ee6b32a27
Create Date: 2026-08-29 21:11:21.046550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9e5f48ead726'
down_revision: Union[str, Sequence[str], None] = '1f3ee6b32a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_de_evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_itinerarios', sa.Integer(), nullable=False),
    sa.Column('itinerarios_con_valoracion', sa.Integer(), nullable=False),
    sa.Column('porcentaje_con_valoracion', sa.Float(), nullable=False),
    sa.Column('total_valoraciones', sa.Integer(), nullable=False),
    sa.Column('con_comentario', sa.Integer(), nullable=False),
    sa.Column('positivas', sa.Integer(), nullable=False),
    sa.Column('neutras', sa.Integer(), nullable=False),
    sa.Column('negativas', sa.Integer(), nullable=False),
    sa.Column('puntuacion_media', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_de_evidencia_fecha'), 'registro_de_evidencia', ['fecha'], unique=False)
    op.create_table('valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('puntuacion', sa.SmallInteger(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('sentimiento', sa.String(length=12), nullable=True),
    sa.Column('confianza_sentimiento', sa.Float(), nullable=True),
    sa.Column('temas', sa.ARRAY(sa.String(length=24)), nullable=False),
    sa.Column('analizado_por', sa.String(length=16), nullable=True),
    sa.Column('version_del_analisis', sa.String(length=120), nullable=True),
    sa.Column('analizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analizado_por IS NULL OR analizado_por IN ('modelo', 'reglas')", name='ck_valoracion_analizado_por'),
    sa.CheckConstraint("sentimiento IS NULL OR sentimiento IN ('positivo', 'neutro', 'negativo')", name='ck_valoracion_sentimiento'),
    sa.CheckConstraint('confianza_sentimiento IS NULL OR confianza_sentimiento BETWEEN 0 AND 1', name='ck_valoracion_confianza'),
    sa.CheckConstraint('puntuacion BETWEEN 1 AND 5', name='ck_valoracion_puntuacion'),
    sa.ForeignKeyConstraint(['itinerario_id'], ['itinerario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso_turistico.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerario_id', 'recurso_id', 'servicio_id', name='uq_valoracion_por_experiencia')
    )
    op.create_index(op.f('ix_valoracion_creado_en'), 'valoracion', ['creado_en'], unique=False)
    op.create_index(op.f('ix_valoracion_itinerario_id'), 'valoracion', ['itinerario_id'], unique=False)
    op.create_index(op.f('ix_valoracion_recurso_id'), 'valoracion', ['recurso_id'], unique=False)
    op.create_index(op.f('ix_valoracion_sentimiento'), 'valoracion', ['sentimiento'], unique=False)
    op.create_index(op.f('ix_valoracion_servicio_id'), 'valoracion', ['servicio_id'], unique=False)
    op.create_index(op.f('ix_valoracion_usuario_id'), 'valoracion', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valoracion_usuario_id'), table_name='valoracion')
    op.drop_index(op.f('ix_valoracion_servicio_id'), table_name='valoracion')
    op.drop_index(op.f('ix_valoracion_sentimiento'), table_name='valoracion')
    op.drop_index(op.f('ix_valoracion_recurso_id'), table_name='valoracion')
    op.drop_index(op.f('ix_valoracion_itinerario_id'), table_name='valoracion')
    op.drop_index(op.f('ix_valoracion_creado_en'), table_name='valoracion')
    op.drop_table('valoracion')
    op.drop_index(op.f('ix_registro_de_evidencia_fecha'), table_name='registro_de_evidencia')
    op.drop_table('registro_de_evidencia')
    # ### end Alembic commands ###
