"""crea proveedores, servicios, disponibilidad y solicitudes de coordinacion

Revision ID: 1f3ee6b32a27
Revises: ce18776b7046
Create Date: 2026-08-29 13:28:26.519688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1f3ee6b32a27'
down_revision: Union[str, Sequence[str], None] = 'ce18776b7046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('distrito', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_demostracion', sa.Boolean(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedor_distrito'), 'proveedor', ['distrito'], unique=False)
    op.create_index(op.f('ix_proveedor_es_demostracion'), 'proveedor', ['es_demostracion'], unique=False)
    op.create_index(op.f('ix_proveedor_usuario_id'), 'proveedor', ['usuario_id'], unique=False)
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('antelacion_minima_horas', sa.Integer(), nullable=False),
    sa.Column('precio_min_soles', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('precio_max_soles', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unidad_precio', sa.String(length=24), nullable=False),
    sa.Column('fecha_referencia', sa.Date(), nullable=False),
    sa.Column('idiomas', sa.String(length=80), nullable=True),
    sa.Column('es_accesible', sa.Boolean(), nullable=False),
    sa.Column('esta_publicado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('transporte', 'alimentacion', 'hospedaje', 'guiado', 'taller', 'artesania')", name='ck_servicio_tipo'),
    sa.CheckConstraint("unidad_precio IN ('por_persona', 'por_grupo', 'por_noche', 'por_hora')", name='ck_servicio_unidad'),
    sa.CheckConstraint('antelacion_minima_horas >= 0', name='ck_servicio_antelacion'),
    sa.CheckConstraint('capacidad_maxima > 0', name='ck_servicio_capacidad'),
    sa.CheckConstraint('precio_max_soles >= precio_min_soles', name='ck_servicio_rango_precio'),
    sa.CheckConstraint('precio_min_soles >= 0', name='ck_servicio_precio_positivo'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso_turistico.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicio_esta_publicado'), 'servicio', ['esta_publicado'], unique=False)
    op.create_index(op.f('ix_servicio_proveedor_id'), 'servicio', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_servicio_recurso_id'), 'servicio', ['recurso_id'], unique=False)
    op.create_index(op.f('ix_servicio_tipo'), 'servicio', ['tipo'], unique=False)
    op.create_table('disponibilidad_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('cupo', sa.Integer(), nullable=False),
    sa.CheckConstraint('cupo > 0', name='ck_disponibilidad_cupo'),
    sa.CheckConstraint('dia_semana BETWEEN 0 AND 6', name='ck_disponibilidad_dia'),
    sa.CheckConstraint('hora_fin > hora_inicio', name='ck_disponibilidad_horas'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id', 'dia_semana', 'hora_inicio', name='uq_disponibilidad_tramo')
    )
    op.create_index(op.f('ix_disponibilidad_servicio_servicio_id'), 'disponibilidad_servicio', ['servicio_id'], unique=False)
    op.create_table('solicitud_coordinacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('itinerario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_servicio', sa.Date(), nullable=False),
    sa.Column('hora_servicio', sa.Time(), nullable=True),
    sa.Column('numero_personas', sa.Integer(), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=160), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=40), nullable=True),
    sa.Column('correo_contacto', sa.String(length=255), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('precio_acordado_soles', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('respuesta_proveedor', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('enviada', 'en_revision', 'contrapropuesta', 'confirmada', 'rechazada', 'cancelada')", name='ck_solicitud_estado'),
    sa.CheckConstraint('numero_personas > 0', name='ck_solicitud_personas'),
    sa.CheckConstraint('precio_acordado_soles IS NULL OR precio_acordado_soles >= 0', name='ck_solicitud_precio'),
    sa.ForeignKeyConstraint(['itinerario_id'], ['itinerario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_coordinacion_creado_en'), 'solicitud_coordinacion', ['creado_en'], unique=False)
    op.create_index(op.f('ix_solicitud_coordinacion_estado'), 'solicitud_coordinacion', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitud_coordinacion_fecha_servicio'), 'solicitud_coordinacion', ['fecha_servicio'], unique=False)
    op.create_index(op.f('ix_solicitud_coordinacion_itinerario_id'), 'solicitud_coordinacion', ['itinerario_id'], unique=False)
    op.create_index(op.f('ix_solicitud_coordinacion_servicio_id'), 'solicitud_coordinacion', ['servicio_id'], unique=False)
    op.create_index(op.f('ix_solicitud_coordinacion_usuario_id'), 'solicitud_coordinacion', ['usuario_id'], unique=False)
    op.create_table('cambio_de_estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('rol_de_quien_cambio', sa.String(length=20), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('ocurrido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_coordinacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cambio_de_estado_ocurrido_en'), 'cambio_de_estado', ['ocurrido_en'], unique=False)
    op.create_index(op.f('ix_cambio_de_estado_solicitud_id'), 'cambio_de_estado', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cambio_de_estado_solicitud_id'), table_name='cambio_de_estado')
    op.drop_index(op.f('ix_cambio_de_estado_ocurrido_en'), table_name='cambio_de_estado')
    op.drop_table('cambio_de_estado')
    op.drop_index(op.f('ix_solicitud_coordinacion_usuario_id'), table_name='solicitud_coordinacion')
    op.drop_index(op.f('ix_solicitud_coordinacion_servicio_id'), table_name='solicitud_coordinacion')
    op.drop_index(op.f('ix_solicitud_coordinacion_itinerario_id'), table_name='solicitud_coordinacion')
    op.drop_index(op.f('ix_solicitud_coordinacion_fecha_servicio'), table_name='solicitud_coordinacion')
    op.drop_index(op.f('ix_solicitud_coordinacion_estado'), table_name='solicitud_coordinacion')
    op.drop_index(op.f('ix_solicitud_coordinacion_creado_en'), table_name='solicitud_coordinacion')
    op.drop_table('solicitud_coordinacion')
    op.drop_index(op.f('ix_disponibilidad_servicio_servicio_id'), table_name='disponibilidad_servicio')
    op.drop_table('disponibilidad_servicio')
    op.drop_index(op.f('ix_servicio_tipo'), table_name='servicio')
    op.drop_index(op.f('ix_servicio_recurso_id'), table_name='servicio')
    op.drop_index(op.f('ix_servicio_proveedor_id'), table_name='servicio')
    op.drop_index(op.f('ix_servicio_esta_publicado'), table_name='servicio')
    op.drop_table('servicio')
    op.drop_index(op.f('ix_proveedor_usuario_id'), table_name='proveedor')
    op.drop_index(op.f('ix_proveedor_es_demostracion'), table_name='proveedor')
    op.drop_index(op.f('ix_proveedor_distrito'), table_name='proveedor')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
