"""La afluencia admite totales anuales y tipo de visitante.

Las series del Ministerio de Cultura vienen por mes; las fichas del MINCETUR
dan el total del año y desglosado por tipo de visitante —extranjeros,
nacionales, locales—.

Repartir un total anual entre doce meses sería inventarse una estacionalidad
que la fuente no mide, y sumar los tres tipos tiraría un desglose que ya está
publicado. Así que `mes` admite nulo («es del año entero») y se añade
`tipo_de_visitante`.


Revision ID: 5ac921e2017f
Revises: 202548ca2ef5
Create Date: 2026-08-30 14:56:20.405614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5ac921e2017f'
down_revision: Union[str, Sequence[str], None] = '202548ca2ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afluencia_historica', sa.Column('tipo_de_visitante', sa.String(length=80), nullable=True))
    op.alter_column('afluencia_historica', 'mes',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_constraint(op.f('uq_afluencia_recurso_periodo'), 'afluencia_historica', type_='unique')
    op.create_unique_constraint('uq_afluencia_recurso_periodo', 'afluencia_historica', ['recurso_id', 'anio', 'mes', 'tipo_de_visitante'])

    # Alembic NO detecta los cambios en las restricciones CHECK: hay que
    # escribirlos a mano. Sin esto, `mes` seria nullable en la columna pero el
    # CHECK seguiria exigiendo 1..12 y cualquier total anual seria rechazado.
    op.drop_constraint('ck_afluencia_mes', 'afluencia_historica', type_='check')
    op.create_check_constraint(
        'ck_afluencia_mes', 'afluencia_historica', 'mes IS NULL OR mes BETWEEN 1 AND 12'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Se borran los totales anuales: sin ellos, `mes` puede volver a ser
    # obligatorio. Es la unica forma de volver atras sin inventarse un mes.
    op.execute("DELETE FROM afluencia_historica WHERE mes IS NULL")
    op.drop_constraint('ck_afluencia_mes', 'afluencia_historica', type_='check')
    op.create_check_constraint('ck_afluencia_mes', 'afluencia_historica', 'mes BETWEEN 1 AND 12')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_afluencia_recurso_periodo', 'afluencia_historica', type_='unique')
    op.create_unique_constraint(op.f('uq_afluencia_recurso_periodo'), 'afluencia_historica', ['recurso_id', 'anio', 'mes'], postgresql_nulls_not_distinct=False)
    op.alter_column('afluencia_historica', 'mes',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_column('afluencia_historica', 'tipo_de_visitante')
    # ### end Alembic commands ###
