"""Añade al proveedor los datos del directorio oficial del MINCETUR.

Hasta la Fase 7 todos los proveedores estaban inventados, porque el proyecto
no tiene convenios con nadie del valle. Sigue sin tenerlos, pero eso no obliga
a inventarlos: el MINCETUR publica el **Directorio Nacional de Prestadores de
Servicios Turísticos Calificados** como datos abiertos con licencia abierta, y
ahí hay 171 prestadores reales en las cuatro provincias de la ruta.

Son empresas que se certificaron voluntariamente ante el Estado y cuyos datos
el Estado publica. Estas columnas guardan lo que las hace verificables —RUC,
certificado, categoría oficial— y de dónde salieron.

`es_demostracion` sigue distinguiendo unos de otros, y la interfaz dice de los
reales que están certificados por el MINCETUR **pero no tienen convenio con
este proyecto**, que es la verdad.


Revision ID: 0e08657630e7
Revises: 0010c8bc61ba
Create Date: 2026-08-30 14:46:37.659378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0e08657630e7'
down_revision: Union[str, Sequence[str], None] = '0010c8bc61ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedor', sa.Column('ruc', sa.String(length=11), nullable=True))
    op.add_column('proveedor', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('proveedor', sa.Column('pagina_web', sa.String(length=255), nullable=True))
    op.add_column('proveedor', sa.Column('clase', sa.String(length=80), nullable=True))
    op.add_column('proveedor', sa.Column('categoria', sa.String(length=80), nullable=True))
    op.add_column('proveedor', sa.Column('certificado', sa.String(length=80), nullable=True))
    op.add_column('proveedor', sa.Column('fuente', sa.String(length=200), nullable=True))
    op.add_column('proveedor', sa.Column('fecha_corte', sa.Date(), nullable=True))
    op.create_index(op.f('ix_proveedor_ruc'), 'proveedor', ['ruc'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proveedor_ruc'), table_name='proveedor')
    op.drop_column('proveedor', 'fecha_corte')
    op.drop_column('proveedor', 'fuente')
    op.drop_column('proveedor', 'certificado')
    op.drop_column('proveedor', 'categoria')
    op.drop_column('proveedor', 'clase')
    op.drop_column('proveedor', 'pagina_web')
    op.drop_column('proveedor', 'direccion')
    op.drop_column('proveedor', 'ruc')
    # ### end Alembic commands ###
