"""crea itinerarios, paradas y tarifas de transporte

Revision ID: ce18776b7046
Revises: ddb2372e02a8
Create Date: 2026-08-29 09:24:33.606648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ce18776b7046'
down_revision: Union[str, Sequence[str], None] = 'ddb2372e02a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarifa_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distrito_origen', sa.String(length=80), nullable=False),
    sa.Column('distrito_destino', sa.String(length=80), nullable=False),
    sa.Column('modo', sa.String(length=16), nullable=False),
    sa.Column('precio_min_soles', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('precio_max_soles', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('duracion_estimada_min', sa.Integer(), nullable=False),
    sa.Column('fecha_referencia', sa.Date(), nullable=False),
    sa.Column('fuente', sa.Text(), nullable=False),
    sa.Column('es_estimado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("modo IN ('caminando', 'combi', 'colectivo', 'taxi')", name='ck_tarifa_modo'),
    sa.CheckConstraint('duracion_estimada_min > 0', name='ck_tarifa_duracion'),
    sa.CheckConstraint('precio_max_soles >= precio_min_soles', name='ck_tarifa_rango'),
    sa.CheckConstraint('precio_min_soles >= 0', name='ck_tarifa_precio_positivo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distrito_origen', 'distrito_destino', 'modo', name='uq_tarifa_ruta_modo')
    )
    op.create_index(op.f('ix_tarifa_transporte_distrito_destino'), 'tarifa_transporte', ['distrito_destino'], unique=False)
    op.create_index(op.f('ix_tarifa_transporte_distrito_origen'), 'tarifa_transporte', ['distrito_origen'], unique=False)
    op.create_table('itinerario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preferencia_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tiempo_total_min', sa.Integer(), nullable=False),
    sa.Column('costo_total_soles', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distancia_total_km', sa.Float(), nullable=False),
    sa.Column('desnivel_total_m', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('generado_por', sa.String(length=16), nullable=False),
    sa.Column('avisos', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('borrador', 'guardado', 'confirmado', 'completado')", name='ck_itinerario_estado'),
    sa.CheckConstraint("generado_por IN ('modelo', 'reglas')", name='ck_itinerario_generado_por'),
    sa.CheckConstraint('costo_total_soles >= 0', name='ck_itinerario_costo'),
    sa.CheckConstraint('tiempo_total_min >= 0', name='ck_itinerario_tiempo'),
    sa.ForeignKeyConstraint(['preferencia_id'], ['preferencia_viaje.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerario_creado_en'), 'itinerario', ['creado_en'], unique=False)
    op.create_index(op.f('ix_itinerario_preferencia_id'), 'itinerario', ['preferencia_id'], unique=False)
    op.create_index(op.f('ix_itinerario_usuario_id'), 'itinerario', ['usuario_id'], unique=False)
    op.create_table('parada_itinerario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerario_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('hora_llegada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=False),
    sa.Column('modo_traslado', sa.String(length=16), nullable=True),
    sa.Column('tiempo_traslado_min', sa.Integer(), nullable=False),
    sa.Column('distancia_traslado_km', sa.Float(), nullable=False),
    sa.Column('desnivel_traslado_m', sa.Float(), nullable=False),
    sa.Column('costo_traslado_min_soles', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('costo_traslado_max_soles', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('origen_del_calculo', sa.String(length=16), nullable=False),
    sa.Column('afluencia_estimada', sa.String(length=8), nullable=True),
    sa.CheckConstraint("modo_traslado IS NULL OR modo_traslado IN ('caminando', 'combi', 'colectivo', 'taxi')", name='ck_parada_modo'),
    sa.CheckConstraint("origen_del_calculo IN ('red_vial', 'linea_recta')", name='ck_parada_origen_calculo'),
    sa.CheckConstraint('hora_salida >= hora_llegada', name='ck_parada_horas'),
    sa.CheckConstraint('orden >= 0', name='ck_parada_orden'),
    sa.ForeignKeyConstraint(['itinerario_id'], ['itinerario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso_turistico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerario_id', 'orden', name='uq_parada_itinerario_orden')
    )
    op.create_index(op.f('ix_parada_itinerario_itinerario_id'), 'parada_itinerario', ['itinerario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parada_itinerario_itinerario_id'), table_name='parada_itinerario')
    op.drop_table('parada_itinerario')
    op.drop_index(op.f('ix_itinerario_usuario_id'), table_name='itinerario')
    op.drop_index(op.f('ix_itinerario_preferencia_id'), table_name='itinerario')
    op.drop_index(op.f('ix_itinerario_creado_en'), table_name='itinerario')
    op.drop_table('itinerario')
    op.drop_index(op.f('ix_tarifa_transporte_distrito_origen'), table_name='tarifa_transporte')
    op.drop_index(op.f('ix_tarifa_transporte_distrito_destino'), table_name='tarifa_transporte')
    op.drop_table('tarifa_transporte')
    # ### end Alembic commands ###
