"""crea el catalogo de recursos turisticos

Revision ID: 3f1515a2371d
Revises: 
Create Date: 2026-08-29 02:37:59.106846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# El proyecto usa tipos geograficos de PostGIS. El autogenerador de Alembic los
# escribe como geoalchemy2.types.Geography(...) pero no anade el import, asi que
# se deja fijo aqui para que toda migracion nueva funcione.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3f1515a2371d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurso_turistico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_mincetur', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('provincia', sa.String(length=80), nullable=False),
    sa.Column('distrito', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=160), nullable=True),
    sa.Column('subtipo', sa.String(length=160), nullable=True),
    sa.Column('url_ficha', sa.Text(), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('altitud_msnm', sa.Integer(), nullable=True),
    sa.Column('fecha_corte', sa.Date(), nullable=True),
    sa.Column('esta_validado', sa.Boolean(), nullable=False),
    sa.Column('esta_vigente', sa.Boolean(), nullable=False),
    sa.Column('motivos_invalidez', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('descripcion_es', sa.Text(), nullable=True),
    sa.Column('descripcion_en', sa.Text(), nullable=True),
    sa.Column('duracion_visita_min', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_mincetur')
    )
    op.create_index(op.f('ix_recurso_turistico_categoria'), 'recurso_turistico', ['categoria'], unique=False)
    op.create_index(op.f('ix_recurso_turistico_distrito'), 'recurso_turistico', ['distrito'], unique=False)
    op.create_index(op.f('ix_recurso_turistico_fecha_corte'), 'recurso_turistico', ['fecha_corte'], unique=False)
    op.create_index('ix_recurso_turistico_nombre_trigrama', 'recurso_turistico', ['nombre'], unique=False, postgresql_using='gin', postgresql_ops={'nombre': 'gin_trgm_ops'})
    op.create_index(op.f('ix_recurso_turistico_provincia'), 'recurso_turistico', ['provincia'], unique=False)
    op.create_table('registro_validacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_recursos', sa.Integer(), nullable=False),
    sa.Column('validados', sa.Integer(), nullable=False),
    sa.Column('vigentes', sa.Integer(), nullable=False),
    sa.Column('con_coordenadas', sa.Integer(), nullable=False),
    sa.Column('porcentaje_validado', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_validacion_fecha'), 'registro_validacion', ['fecha'], unique=False)
    op.create_table('horario_atencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=False),
    sa.Column('hora_apertura', sa.Time(), nullable=False),
    sa.Column('hora_cierre', sa.Time(), nullable=False),
    sa.CheckConstraint('dia_semana BETWEEN 0 AND 6', name='ck_horario_dia_semana'),
    sa.CheckConstraint('hora_cierre > hora_apertura', name='ck_horario_cierre_posterior'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso_turistico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurso_id', 'dia_semana', 'hora_apertura', name='uq_horario_recurso_dia_apertura')
    )
    op.create_index(op.f('ix_horario_atencion_recurso_id'), 'horario_atencion', ['recurso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_horario_atencion_recurso_id'), table_name='horario_atencion')
    op.drop_table('horario_atencion')
    op.drop_index(op.f('ix_registro_validacion_fecha'), table_name='registro_validacion')
    op.drop_table('registro_validacion')
    op.drop_index(op.f('ix_recurso_turistico_provincia'), table_name='recurso_turistico')
    op.drop_index('ix_recurso_turistico_nombre_trigrama', table_name='recurso_turistico', postgresql_using='gin', postgresql_ops={'nombre': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_recurso_turistico_fecha_corte'), table_name='recurso_turistico')
    op.drop_index(op.f('ix_recurso_turistico_distrito'), table_name='recurso_turistico')
    op.drop_index(op.f('ix_recurso_turistico_categoria'), table_name='recurso_turistico')
    op.drop_table('recurso_turistico')
    # ### end Alembic commands ###
